// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdsEMKji7HlKn-4TvT-1P5z80zf2l9cLk',
    appId: '1:453421016006:web:0eb64a5cf3cd416b17c8c7',
    messagingSenderId: '453421016006',
    projectId: 'stacked-demo-project',
    authDomain: 'stacked-demo-project.firebaseapp.com',
    storageBucket: 'stacked-demo-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQHy5sGLIl3Y96q0du7t2T9iVmCBgetTs',
    appId: '1:453421016006:android:687b0531da0089fa17c8c7',
    messagingSenderId: '453421016006',
    projectId: 'stacked-demo-project',
    storageBucket: 'stacked-demo-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM5IDdc6KGov9JRvuVsDpxWbGWaNe-Cos',
    appId: '1:453421016006:ios:5e5944063f8467d717c8c7',
    messagingSenderId: '453421016006',
    projectId: 'stacked-demo-project',
    storageBucket: 'stacked-demo-project.appspot.com',
    iosClientId: '453421016006-pbe8s5ea8vheoap36hb5ooirhj2jt4po.apps.googleusercontent.com',
    iosBundleId: 'com.example.stackedDemo',
  );
}
